### ISSUE TITLE
Graph doesn't work when Canopy server run with systemd

### ISSUE THREAD

**Issue by zareenc** [roscloud/roscloud_server#16]
Error log:
```
Feb 01 13:02:36 roomba-3 sh[24026]: 2018/02/01 13:02:36 http: panic serving 192.168.1.113:52010: open graph/graph.html: no such file or directory
Feb 01 13:02:36 roomba-3 sh[24026]: goroutine 33 [running]:
Feb 01 13:02:36 roomba-3 sh[24026]: net/http.(*conn).serve.func1(0xc42007e140)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/net/http/server.go:1697 +0xd0
Feb 01 13:02:36 roomba-3 sh[24026]: panic(0x855620, 0xc4201625a0)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/runtime/panic.go:491 +0x283
Feb 01 13:02:36 roomba-3 sh[24026]: text/template.Must(0x0, 0xb240e0, 0xc4201625a0, 0x0)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/text/template/helper.go:23 +0x54
Feb 01 13:02:36 roomba-3 sh[24026]: main.graphHandler.ServeHTTP(0xc420011f20, 0xb29b60, 0xc4201a20e0, 0xc420102000)
Feb 01 13:02:36 roomba-3 sh[24026]:         /home/zareenc/go/src/github.com/canopy-ros/canopy_server_comm/main.go:328 +0x12c2
Feb 01 13:02:36 roomba-3 sh[24026]: net/http.(*ServeMux).ServeHTTP(0xb66e20, 0xb29b60, 0xc4201a20e0, 0xc420102000)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/net/http/server.go:2254 +0x130
Feb 01 13:02:36 roomba-3 sh[24026]: net/http.serverHandler.ServeHTTP(0xc42007dad0, 0xb29b60, 0xc4201a20e0, 0xc420102000)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/net/http/server.go:2619 +0xb4
Feb 01 13:02:36 roomba-3 sh[24026]: net/http.(*conn).serve(0xc42007e140, 0xb2a260, 0xc4204923c0)
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/net/http/server.go:1801 +0x71d
Feb 01 13:02:36 roomba-3 sh[24026]: created by net/http.(*Server).Serve
Feb 01 13:02:36 roomba-3 sh[24026]:         /usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by zareenc** [comment]
The `GOPATH` was undefined in the service environment, making the service unable to find the graph files, so I added `GOPATH` go the service environment file.
